version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      soma-root:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /packages/soma-heart
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      soma-heart:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /packages/soma-sense
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      soma-sense:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
